name: TheoremSense
channels:
  - defaults
dependencies:
  - python=3.10
  - huggingface_hub
  - ca-certificates
  - openssl
  - datasets
  - certifi
  - fsspec=2023.9.2
  - jupyterlab
  - ipywidgets
  - matplotlib
  - seaborn
  - accelerate
  - bitsandbytes
  - pip:
      - vllm
      - flash-attn